version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: corragil
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db